[package]
name = "rust-lib-template"
description = "Rust library template"
version = "0.1.0"
edition = "2021"

categories = [
    "rust",
    "rust::library"
]
authors = [
    "Vahid V. <vhid.vz@gmail.com>",
]

readme = "README.md"
documentation = "https://docs.rs/bitflags"

keywords = ["rust", "library-template"]
homepage = "https://github.com/vhidvz/rust-lib-template"
repository = "https://github.com/vhidvz/rust-lib-template.git"

license = "MIT"
exclude = ["/docs"]
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
